server:
  port: 8001

spring:
  application:
    name: TicketService

eureka:
  instance:
    prefer-ip-address: true
    #hostname: eureka7001.com
    instance-id: eureka7001.com
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
